name: Build Native

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/main/resources/org/xerial/snappy/VERSION'
      - 'Makefile'
      - 'Makefile.common'
      - '**/*.h'
      - '**/*.cpp'
      - .github/workflows/build-native.yml

jobs:
  build:
    name: Build native libraries
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.output.outputs.ref }}
      repo: ${{ steps.output.outputs.repo }}
    steps:
      - uses: actions/checkout@v3
      - name: Build native libraries
        # run: make clean-native native-all
        run: make clean-native native
        env:
          OCI_EXE: docker
      - name: Upload native libraries
        uses: actions/upload-artifact@v3
        with:
          name: native-libs
          path: src/main/resources/org/xerial/snappy/native/
      # This will set the branch to use:
      # - if workflow_dispatch, use the branch that was chosen when running the workflow
      # - if it is a comment on a PR, and the trigger matches, use the PR branch
      - name: Set job output
        id: output
        run: |
          echo "::echo::on"
          if [[ "${{ github.event_name == 'workflow_dispatch' }}" == 'true' ]]
          then
            echo "ref=${{ github.ref_name }}" >> $GITHUB_OUTPUT
            echo "repo=${{ github.repository }}" >> $GITHUB_OUTPUT
          else
            echo "ref=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
            echo "repo=${{ github.event.pull_request.head.repo.full_name }}" >> $GITHUB_OUTPUT
          fi

  push:
    permissions:
      # write permission is required for pushing commits
      contents: write
    name: Push new native libraries to branch
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
	run: gh pr checkout ${{ github.event.pull_request.number }}
      #- uses: actions/checkout@v3
      #  with:
      #    repository: ${{ needs.build.outputs.repo }}
      #    ref: ${{ needs.build.outputs.ref }}
      - name: Download native libraries
        uses: actions/download-artifact@v3
        with:
          name: native-libs
          path: src/main/resources/org/xerial/snappy/native/
      - run: git status
      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update native libraries'
          default_author: github_actions
